[リカバリ版] クックパッドのスクレイピングコードを実装
makitchen/get_multiple_recipes pull request #13
Opened 2021-03-29 10:31 UTC by makitchen

- close https://github.com/makitchen/get_multiple_recipes/issues/3

2021-03-30 06:51 UTC, morudara requested changes
ご確認お願いしますー

2021-03-30 06:51 UTC, morudara commented on scraping-cookpad/get_recipe_urls.py
> +        category_url_list.append(full_path_category_url)
forで回してる処理とfで文字列結合してURL作成してることをコメント書こう

2021-03-30 06:51 UTC, morudara commented on scraping-cookpad/get_recipe_urls.py
> +        # 対象カテゴリのページを8ページ分回すため、対象カテゴリをひとつずつ取り出しているforの中に記述
10ページ回してるので、コメント修正しよう

2021-03-30 06:51 UTC, morudara commented on scraping-kurashiru/get_access_detail_pages.py
> +def recipe_info(detail_recipe_url):
recipe_infoを取得だから、 `get_recipe_info` という関数名がいいかな

2021-03-30 06:51 UTC, morudara commented on scraping-cookpad/get_access_detail_pages.py
> +    return recipe_food_stuff_info
ファイル全体で変数、関数のfood_stuffという命名をrecipe_ingredientsに変えよう

2021-03-30 06:51 UTC, morudara commented on README.md
> + - [スクレイピング結果CSV](./sirogohan_recipe_info.csv)
READMEにクックパッドのCSVリンクと、実行方法も書こう_

2021-03-30 15:02 UTC, makitchen commented on scraping-cookpad/get_access_detail_pages.py
> +    return recipe_food_stuff_info
対応しました(*･ω･)/

2021-03-30 15:02 UTC, makitchen commented on scraping-kurashiru/get_access_detail_pages.py
> +def recipe_info(detail_recipe_url):
対応しました(*･ω･)/

2021-03-30 15:02 UTC, makitchen commented on scraping-cookpad/get_recipe_urls.py
> +        # 対象カテゴリのページを8ページ分回すため、対象カテゴリをひとつずつ取り出しているforの中に記述
対応しました(*･ω･)/

2021-03-30 15:02 UTC, makitchen commented on scraping-cookpad/get_recipe_urls.py
> +        category_url_list.append(full_path_category_url)
対応しました(*･ω･)/

2021-04-04 09:50 UTC, morudara approved these changes
LGTM！

2021-04-04 11:45 UTC, merged