白ごはん.comのスクレイピングコードを実装
makitchen/get_multiple_recipes pull request #6
Opened 2021-03-18 07:27 UTC by makitchen

- close https://github.com/makitchen/get_multiple_recipes/issues/2

2021-03-28 10:07 UTC, morudara requested changes
指摘事項です。ご確認お願いしますー

2021-03-28 10:07 UTC, morudara commented on scraping-sirogohan/main.py
> +# 順番はmainから読み込む順番にする
`# 順番はmainから読み込む順番にする`
このコメントアウト要らないかな。元々logファイルを複数にしようとした時のもので、logファイルは1つにしたから不要になった

2021-03-28 10:07 UTC, morudara commented on scraping-sirogohan/text_re.py
> +# これを、エスケープシーケンスと呼ぶ。正規表現を使用する際にエスケープシーケンスは邪魔になってしまう可能性があるので、
このファイル以下で消そう
https://awesome-linus.com/2020/06/29/git-revoke-wrong-commit/#toc13

2021-03-28 10:14 UTC, morudara requested changes

2021-03-28 10:14 UTC, morudara commented on scraping-sirogohan/get_access_detail_pages.py
> +def recipe_info(recipe_url):
`recipe_info` を取得するわけだから、 `get_recipe_info` にしよう

2021-03-28 10:22 UTC, morudara requested changes

2021-03-28 10:22 UTC, morudara commented on scraping-sirogohan/get_recipe_urls.py
> +            writecsv.writerow([recipe_detail_url])
せっかくなので、CSVにヘッダーを表示しよう
ヘッダーがあると、それぞれの値が何の項目なのかCSVだけ見てわかるので
https://www.mathpython.com/ja/python-csv-write-header/

2021-03-28 10:27 UTC, morudara requested changes

2021-03-28 10:27 UTC, morudara commented on scraping-sirogohan/get_access_detail_pages.py
> +
せっかくなので、CSVにヘッダーを表示しよう
ヘッダーがあると、それぞれの値が何の項目なのかCSVだけ見てわかるので
https://www.mathpython.com/ja/python-csv-write-header/

2021-03-29 09:15 UTC, makitchen commented on scraping-sirogohan/get_recipe_urls.py
> +def get_next_page(driver):
対応しました！

2021-03-29 09:15 UTC, makitchen commented on scraping-sirogohan/get_recipe_urls.py
> +    # 正規表現を使用し、必要な文字列のみ抜き出す
対応しました(｀･ω･´)

2021-03-29 09:15 UTC, makitchen commented on scraping-sirogohan/get_recipe_urls.py
> +        # クラス名"next"を使用し、次ページへ飛ぶ
対応しました♬

2021-03-29 09:15 UTC, makitchen commented on scraping-sirogohan/get_recipe_urls.py
> +        recipe_detail_full_path_url_list = search_recipe_detail_urls(current_url)
対応しました！

2021-03-29 09:16 UTC, makitchen commented on scraping-sirogohan/get_recipe_urls.py
> +        recipe_detail_url_list.append(detail_urls)
以下に記載しています<(_ _)>
https://github.com/makitchen/get_multiple_recipes/pull/6/files#diff-0fed4ea3cb73ecc1a693e104fe1fb8e4854cccbbb6913a92d56139b0283429adR86

2021-03-29 09:16 UTC, makitchen commented on scraping-sirogohan/get_recipe_urls.py
> +    # 取得したURLをSIROGOHAN_TOP_URL("https://www.sirogohan.com")と結合させ、正しい絶対パスのURLに修正
対応しました！

2021-03-29 09:16 UTC, makitchen commented on scraping-sirogohan/main.py
> +# 順番はmainから読み込む順番にする
対応しました(｀･ω･´)

2021-03-29 09:16 UTC, makitchen commented on scraping-sirogohan/get_access_detail_pages.py
> +def recipe_info(recipe_url):
対応しました♬

2021-03-29 09:17 UTC, makitchen commented on scraping-sirogohan/get_access_detail_pages.py
> +
対応しました🙌

2021-03-29 09:58 UTC, closed without merging

2021-03-29 13:36 UTC, makitchen commented on README.md
> + - [スクレイピング結果CSV](./sirogohan_recipe_info.csv)
対応しました👌

2021-03-29 13:36 UTC, makitchen commented on scraping-sirogohan/text_re.py
> +# これを、エスケープシーケンスと呼ぶ。正規表現を使用する際にエスケープシーケンスは邪魔になってしまう可能性があるので、
対応しました👌