kurashiruのスクレイピングコードを実装
makitchen/get_multiple_recipes pull request #8
Opened 2021-03-22 12:28 UTC by makitchen

- close https://github.com/makitchen/get_multiple_recipes/issues/5

2021-03-28 10:29 UTC, morudara requested changes
指摘事項です。ご確認お願いしますー

2021-03-28 10:29 UTC, morudara commented on scraping-kurashiru/get_access_detail_pages.py
> +            recipe_info(detail_recipe_url)
このforで回して `recipe_info` を呼んでる処理についてもコメントを書こう

2021-03-28 10:29 UTC, morudara commented on scraping-kurashiru/get_access_detail_pages.py
> +def recipe_info(detail_recipe_url):
`recipe_info` を取得するわけだから、 `get_recipe_info` にしよう

2021-03-28 10:29 UTC, morudara commented on scraping-kurashiru/get_access_detail_pages.py
> +        )
せっかくなので、CSVにヘッダーを表示しよう
ヘッダーがあると、それぞれの値が何の項目なのかCSVだけ見てわかるので
https://www.mathpython.com/ja/python-csv-write-header/

2021-03-28 10:29 UTC, morudara commented on scraping-kurashiru/get_recipe_urls.py
> +    # カテゴリのURLのリストを繰り返し、各カテゴリ毎に4ページ分ずつ取得
>     # カテゴリのURLのリストを繰り返し、各カテゴリ毎に4ページ分ずつ取得
6ページ対応することになったのでこのコメントも直そう

2021-03-28 10:29 UTC, morudara commented on scraping-kurashiru/get_recipe_urls.py
> +        category_url = f"{category_url}/?page={str(page_count + 1)}"
クックパッドでやったように、処理の最初に `page_count` の値に +1しておこう

2021-03-30 07:18 UTC, makitchen commented on scraping-kurashiru/get_access_detail_pages.py
> +            recipe_info(detail_recipe_url)
対応しました(`･ω･´)b

2021-03-30 07:18 UTC, makitchen commented on scraping-kurashiru/get_access_detail_pages.py
> +def recipe_info(detail_recipe_url):
対応しました(`･ω･´)b

2021-03-30 07:18 UTC, makitchen commented on scraping-kurashiru/get_access_detail_pages.py
> +        )
対応しました(`･ω･´)b

2021-03-30 07:19 UTC, makitchen commented on scraping-kurashiru/get_recipe_urls.py
> +    # カテゴリのURLのリストを繰り返し、各カテゴリ毎に4ページ分ずつ取得
対応しました(`･ω･´)b

2021-03-30 07:19 UTC, makitchen commented on scraping-kurashiru/get_recipe_urls.py
> +        category_url = f"{category_url}/?page={str(page_count + 1)}"
対応しました(`･ω･´)b

2021-04-04 11:44 UTC, closed without merging